### ISSUE TITLE
Question re: diagrams in documentation

### ISSUE THREAD

**Issue by cmuhire** [eigr/eigr.github.io#1]
Hi,

First of all, cool project and thanks for open sourcing it!

This is the first of its kind I've seen in the Elixir ecosystem, most "cloud native" infrastructure tooling these days seems to be built in Go, so it's good to see more growth in this area as the BEAM is a great fit for this. Keen to play around with this :)

I ended up here from this talk given by Marcel at the ACM SIGPLAN Erlang session (https://www.youtube.com/watch?v=jVf0QqNb3qk) which lead me to the documentation site where I then got starstruck by the beautiful ASCII diagrams! Never seen their kind before! Here's an example from this repo https://github.com/eigr/eigr.github.io/blob/main/eigr_io/docs/concepts/inversion-of-state.md

 I basically just wanted to ask what tool you use to generate them?  😅

I know I'm misusing the Github issue for this but couldn't think of a better way of reaching out.

Thanks a lot & good luck with the project!

**Comment by marcellanz** [comment]
Hi @cmuhire thank for reaching out. I've used https://monodraw.helftone.com to draw these diagrams. It's a really well made application with a lot of attention to details.

>Thanks a lot & good luck with the project!

thanks :) and thanks for watching out talk. It was our very first talk about our project. If you like to discuss or have questions, we have a discord channel here: https://discord.gg/Y55eZpyvNs

Best regards, Marcel

**Comment by cmuhire** [comment]
Hi @marcellanz , thanks so much for the prompt response! I'll checkout the tool & discord channel :100:
